### ISSUE TITLE
User can see their car.

### ISSUE THREAD

**Issue by jiannicariaga** [jiannicariaga/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x]  Add a body selector to the CSS.
  - [x]  Add a background color or image to the body selector.
- [x]  Add an image tag to the HTML.
  - [x] Set the image to a top-level view of a vehicle.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
