### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by jiannicariaga** [jiannicariaga/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a data model in the JS that includes information about which way the vehicle is facing.
- [x] Create an event listener for when the user presses a directional key.
  - [x] Update the image tag's styling to turn in the direction that was pressed.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
