### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by jiannicariaga** [jiannicariaga/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add vehicle's x and y coordinates to the data model.
- [x] Add absolute positioning to the vehicle's styling.
  - [x] Set vehicle's default x and y coordinates. 
- [x] Add an event listener for when the player starts the vehicle.
  - [x] Update the vehicle's top and left offset styles when vehicle is started.
  - [x] Add movement to the vehicle (every 16ms).
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
