### ISSUE TITLE
User can stop their car.

### ISSUE THREAD

**Issue by jiannicariaga** [jiannicariaga/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add Boolean variable to data model to indicate whether the vehicle is started.
  - [x] Update callback function to include and "toggle" Boolean variable.
  - [x] Stop updating the vehicle's coordinates if the car is stopped.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
